// Autogenerated

package main

type ComplexType struct {
	b bool
	s uint
}

func (c *ComplexType) EncodeSSZ() ([]byte, error) {
	return nil, nil
}

func (c *ComplexType) DecodeSSZ(b []byte) error {
	return nil
}
